### ISSUE TITLE
Error loading the ontology

### ISSUE THREAD

**Issue by narjesHN** [flekschas/owl2neo4j#1]
Hi, 
I tried to use owl2neo4j to import pizza ontology but I'm getting this error:
**Checking Neo4J at http://localhost:7474... [32m?[0m
Checking credentials for Neo4J... [32m?[0m
Loading PIZZA... [31mError loading the ontology[0m
[31mnull[0m**
Any suggestions on how to fix this?

**Comment by nasrinazif** [comment]
Hi,
I got the same error

**Comment by Khalefa** [comment]
Me too. 
Any help!!

**Comment by nasrinazif** [comment]
@Khalefa I used https://github.com/jbarrasa/neosemantics and it perfectly worked for me

**Comment by Khalefa** [comment]
thanks !!

**Comment by amirhsh** [comment]
@nasrinazif Thanks for your link.
Just a question about it.
Can I implement an ontology in protege and import it to neo4j by neosemantics?

**Comment by flekschas** [comment]
@narjesHN @nasrinazif @Khalefa 
Please provide some more background information, i.e., which OS are you using, which version of owl2neo4j are you using etc. The tool works for me on macOS and linux.

**Update**:
I just successfully tested it on macOS 10.12.6 with https://github.com/owlcs/pizza-ontology/blob/master/pizza.owl, Owl2Neo4j `v0.7.0`, and Neo4J `v2.3.1`. Without further information I can't really help.

**Comment by flekschas** [comment]
@narjesHN @nasrinazif @Khalefa

Sorry this is simply a typo in the documentation. Make sure to pass in a **path** for the `o` parameter. The following works **if** `pizza.owl` is in the same directory as you are:

```
java -jar /path/to/owl2neo4j.jar -o ./pizza.owl -n "Pizza Ont" -a pizza
```

to check if the path is correct you can do:

```
[ -f ./pizza.owl ] && echo "Found" || echo "Not found"
```

Note: Make sure to provide a valid path to `owl2neo4j.jar`!
