### ISSUE TITLE
Error loading [the] ontology

### ISSUE THREAD

**Issue by colingoldberg** [flekschas/owl2neo4j#2]
Hi,

I know that some time has passed, and I do appreciate that you have provided this tool. I successfully installed and built it on macos 10.13.4. I tried it on the pizza.owl file, and got a brief error message "Error loading the ontology\nnull".

I tried with an RDF/XML pizza file, and also with one saved as OWL/XML using Protege.
[pizza.owl.txt](https://github.com/flekschas/owl2neo4j/files/1996449/pizza.owl.txt)
[pizza.owl.xml.txt](https://github.com/flekschas/owl2neo4j/files/1996450/pizza.owl.xml.txt)

I hope you are willing and able to help with this. A more detailed error message would be a start.

`
$ java -jar /usr/local/share/owl2neo4j/dist/owl2neo4j.jar -o pizza.owl -p xxx -n "Pizza Ontology" -a pizza
Checking Neo4J at http://localhost:7474... ✓
Checking credentials for Neo4J... ✓
Loading PIZZA... Error loading the ontology
null

`

**Comment by flekschas** [comment]
@colingoldberg Sorry for the belated reply. Somehow I don't get automatic notifications :(

Anyway, is this still an issue and if so, could you let me know which version of Java you're using? I am afraid this might be the issue because I haven't tested it on newer version in a while.

**Comment by colingoldberg** [comment]
Thanks for responding. My java version is:

$ java --version
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

It would be nice to have a debug/verbose option to be able to see what's going on.

Regards

**Comment by flekschas** [comment]
Okay, I pretty sure it's an issue with the Java version. I unfortunately don't have a lot of time maintaining the package but I'll try to take a look on the weekend.

There's a verbosity (`-v`) flag already, which increases the output. Is that what you were thinking of?

**Comment by flekschas** [comment]
Quick note to myself: JDK9 is [obsolete](https://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html), so I'll only focus on the two LTS versions JDK8 and JDK11 (once it's out)

**Comment by flekschas** [comment]
@colingoldberg I assume the issue was `-o pizza.owl`, which should have been `-o ./pizza.owl`. I've updated the tool to ensure that both work and tested it in Java 8. I hope it's working now but I can't ensure it works with Java 9 as I am only planning to support LTS versions from now on (so Java 8 and the upcoming version 11.
